name: docker

concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  release:
    types: [ created ]
  repository_dispatch:
    types: [ docker ]
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: jo3mccain
  REGISTRY: hub.docker.com

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v3
    - name: Publish
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        context: .
        dockerfile: Dockerfile
        name: ${{ env.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        platforms: linux/amd64
        snapshot: true
        tags: "latest"
        username: ${{ env.DOCKERHUB_USERNAME }}